- package-lock.json
- package.json
- src/config/environment.ts
- src/constants/emailTransporter.ts
- src/constants/httpMessage.ts
- src/constants/routes.ts
- src/controllers/auth.controller.ts
- src/controllers/otp.controller.ts
- src/middlewares/auth.middleware.ts
- src/middlewares/otp.middleware.ts
- src/models/otpVerification/index.ts
- src/models/otpVerification/otpVerification.doc.ts
- src/models/user/index.ts
- src/models/user/user.doc.ts
- src/routers/v1/auth.routes.ts
- src/services/authService/signup.service.ts
- src/services/user.service.ts
- src/types/enum/emailType.enum.ts
- src/types/enum/role.enum.ts
- src/types/global.d.ts
- src/types/http/otp.type.ts
- src/types/http/signup.type.ts
- src/types/otpVerification.type.ts
- src/utils/catchErrors.ts
- src/utils/mailOptions.ts
- src/utils/otp.ts
- src/validations/authValidation/signup.validation.ts
- defined `sendOtpVerificationEmail` & `verifyOTP` middlewares
- defined `/sendotp` & `/verify` routes (apis)
> feat: implemented sign up process with OTP verification

- src/controllers/auth.controller.ts
- src/routers/v1/auth.routes.ts
Sign up account without OTP verification
> feat/signup: omitted OTP verification

- src/services/product.service.ts
api: `/products?page=2&limit=2&search=2`
> feat/product: defined get all product api with pagination

- src/controllers/product.controller.ts
- src/models/product/product.doc.ts
- src/routers/v1/customerRoutes/product.routes.ts
- src/services/product.service.ts
- src/types/http/product.type.ts
- src/utils/jwt.ts
- src/utils/slug.ts
- Get all:  `GET: /products` with params: _page_, _limit_, _search_
- Create one: `POST: /products` 
- Update one: `PUT: /products`
- Delete one from database: `DELETE: /products` with query param: __id_
- Switch active or inactive product: `PATCH: /product` with query param: __id_
> feat/product: defined APIs for product

- src/constants/pagination.ts
- src/constants/routes.ts
- src/constants/validation.ts
- src/controllers/user.controller.ts
- src/middlewares/auth.middleware.ts
- src/models/user/user.doc.ts
- src/routers/v1/customerRoutes/address.routes.ts
- src/routers/v1/customerRoutes/index.ts
- src/routers/v1/customerRoutes/user.route.ts
- src/routers/v1/customerRoutes/user.routes.ts
- src/routers/v1/index.ts
- src/services/product.service.ts
- src/services/user.service.ts
- src/types/http/pagination.type.ts
- src/types/http/user.type.ts
- src/types/model/user.type.ts
- src/utils/catchErrors.ts
- src/validations/user.validation.ts
API endpoint **`GET: /users`** with paginating query params: `page`, `limit` and `search` (search by firstName or lastName)
> feat/user: defined api for finding users

- src/controllers/user.controller.ts
- src/routers/v1/customerRoutes/address.routes.ts
- src/routers/v1/customerRoutes/user.routes.ts
- src/services/user.service.ts
- Only delete from db, but not show to response yet
> feat: defined api for deleting address

- src/controllers/order.controller.ts
- src/middlewares/order.middleware.ts
- src/routers/v1/customerRoutes/index.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/services/order.service.ts
- src/utils/object.ts
- Query params :
- __id_ 
- _userID_
- _orderStatusID_
- _paymentMethodID_
- _storeID_
- If role is **_customer_**, userID is required
- If role is **_seller_**, storeID is required
> feat/order: created middleware to checking user role

- src/middlewares/auth.middleware.ts
- src/routers/v1/customerRoutes/address.routes.ts
- src/routers/v1/customerRoutes/user.routes.ts
- checkCustomerPermission()
- checkSellerPermission()
- checkAdminPermission()
> feat/RBAC: updated checkRolePermission function to accepting multiple roles

- src/middlewares/order.middleware.ts
- src/routers/v1/adminRoutes/index.ts
- src/routers/v1/adminRoutes/order.routes.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/routers/v1/sellerRoutes/index.ts
- src/routers/v1/sellerRoutes/order.routes.ts
- src/types/http/order.type.ts
- src/validations/order.validation.ts
- src/validations/pagination.validation.ts
- delete checkRole middleware of order
- created order validations for customer & seller
> feat: created order validation for each user role

- src/controllers/order.controller.ts
- src/routers/v1/adminRoutes/index.ts
- src/routers/v1/adminRoutes/order.routes.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/routers/v1/sellerRoutes/order.routes.ts
- src/services/order.service.ts
- _id : orderID
- orderStatusID
> feat: defined api for updating order status

- src/controllers/product.controller.ts
- src/routers/v1/customerRoutes/product.routes.ts
- src/services/product.service.ts
- src/types/enum/productQuality.enum.ts
- src/utils/object.ts
1. GET: `/products/id/:productID`
2. GET: `/products/slug/:productSlug`
3. GET: `/products` with query params:
> feat: defined apis for finding product + added additional params for filtering product list

- src/services/product.service.ts
Added `storeID` query params to filtering products
- storedID : [ObjectID]
> feat: updated apis for finding product

- src/services/cart.service.ts
> feat: formatted response data for finding cart items

- src/constants/routes.ts
- src/controllers/store.controller.ts
- src/routers/v1/customerRoutes/index.ts
- src/routers/v1/customerRoutes/store.route.ts
- src/routers/v1/sellerRoutes/index.ts
- src/routers/v1/sellerRoutes/store.route.ts
- src/services/store.service.ts
1. GET: `/stores/u/:userID`
2. GET: `/stores/:storeID`
> feat: defined apis for finding store info

- src/apis/ghn.ts
- src/apis/momo.ts
- src/config/axios.ts
- src/config/environment.ts
- src/controllers/store.controller.ts
- src/models/address/address.doc.ts
- src/models/store/store.doc.ts
- src/routers/v1/customerRoutes/store.route.ts
- src/services/order.service.ts
- src/services/store.service.ts
- src/services/user.service.ts
- src/types/global.d.ts
- src/types/http/ghn.type.ts
- src/types/http/store.type.ts
- src/types/model/address.type.ts
- src/types/model/store.type.ts
- src/types/model/user.type.ts
- src/validations/user.validation.ts
- name
- description
- phoneNumber
- userID
- address : `_AddressProps_`
- Request: `type CreateStoreRequestProps = StoreProps & Pick<UserProps, 'phoneNumber'>`
- Response: `StoreProps'
> feat: defined apis for creating user's store

- src/apis/ghn.ts
- src/config/axios.ts
- src/controllers/order.controller.ts
- src/middlewares/errorHandler.middleware.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/services/order.service.ts
- src/types/http/order.type.ts
- src/validations/shipping.validation.ts
Request body:
- `shopid`: _GHN shop's ID_
- `service_type_id`: 2 (is default)
- `to_district_id`
- `to_ward_code`
- `weight`: gram,
- `from_district_id`
- `from_ward_code`
> feat: defined api for calculating shipping fee of order

- src/apis/ghn.ts
- src/controllers/user.controller.ts
- src/models/address/address.doc.ts
- src/routers/v1/customerRoutes/address.routes.ts
- src/services/address.service.ts
- src/types/http/address.type.ts
- src/types/http/ghn.type.ts
- src/types/model/address.type.ts
Body: 
- `province_id`: number
Body: 
- `district_id`: number
> feat: defined apis for getting provinces, districts and wards

- src/controllers/order.controller.ts
- src/models/order/order.doc.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/services/order.service.ts
- src/types/enum/paymentMethod.enum.ts
- src/types/http/order.type.ts
- src/types/model/order.type.ts
- userID
- total
- paymentMethodID
- receiverAddress : `AddressProps`
- orders: **`CreatedOrderProps[]`** (⬇️)
- storeID
- total
- note
- shipmentCost
- items: **`MoMoPaymentItemsProps[]`** (⬇️)
- File: _momoPayment.type.ts_ 
##
> feat: added COD payment feature

- src/services/order.service.ts
- src/types/http/order.type.ts
- src/validations/shipping.validation.ts
> feat: added additional request props for calculating shipping fee

- src/services/user.service.ts
- `_id`: id of userID or storeID (only for userID in this API)
- address: `AddressProps`
> chore: changed type of request body for creating address

- package-lock.json
- package.json
- src/apis/sms.ts
- src/controllers/user.controller.ts
- src/middlewares/otp.middleware.ts
- src/models/otpVerification/otpVerification.doc.ts
- src/routers/v1/auth.routes.ts
- src/routers/v1/customerRoutes/address.routes.ts
- src/routers/v1/customerRoutes/user.routes.ts
- src/services/user.service.ts
- src/types/http/otp.type.ts
- src/types/http/user.type.ts
- src/types/model/otpVerification.type.ts
- src/utils/phone.ts
- src/validations/user.validation.ts
- `phoneNumber`: string + must be start with `+84` (using [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js) to validating)
#
- `phoneNumber`
- `_id`
- `otp`
#
- _id
- firstName
- lastName
- dateOfBirth
> feat: defined apis for identifying phone number

- src/constants/httpMessage.ts
- src/services/user.service.ts
- src/types/http/address.type.ts
- _id: userID or storeID (only for userID in this api)
- addressID
_***Note**:_ The deleted address is not the default address
#
> feat: defined api for deleting user's address 

- src/apis/ghn.ts
- src/config/axios.ts
- src/controllers/order.controller.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/services/order.service.ts
- src/types/http/ghn.type.ts
- src/types/http/order.type.ts
- src/validations/shipping.validation.ts
- `shop_id`: required
- `from_district`: required
- `to_district`: required
{
- `service_id`: number
- `short_name`: string
-  `service_type_id`: number.
} [ ]
> feat: defined a api for getting available delivery service

- src/models/product/product.doc.ts
- src/services/cloudinary.service.ts
- src/services/order.service.ts
- src/services/product.service.ts
- Decrease the product quantity when a new order is placed
- Only selecting products with quantity greater than 0
> perf: selecting products with a quantity greater than 0

- src/models/product/product.doc.ts
- src/routers/v1/customerRoutes/product.routes.ts
- src/types/model/product.type.ts
- src/validations/product.valitdation.ts
- . . .
- `weight`: number - required (_gram_)
- `height`: number - required _(cm)_
- `width`: number - required _(cm)_
- `length`: number - required _(cm)_
- `address`: AddressProps - required
> feat: added address and size properties to the product schema

- src/constants/routes.ts
- src/controllers/user.controller.ts
- src/models/user/user.doc.ts
- src/routers/v1/customerRoutes/user.routes.ts
- src/services/user.service.ts
- src/types/model/user.type.ts
> feat: defined api for finding user by slug

- src/constants/routes.ts
- src/controllers/category.controller.ts
- src/models/category/category.doc.ts
- src/routers/v1/customerRoutes/category.routes.ts
- src/services/category.service.ts
- src/services/cloudinary.service.ts
- src/types/http/category.type.ts
- src/types/model/category.type.ts
- src/validations/category.valiation.ts
- `name`
- `parendID`
- `image`: String
> feat: defined APIs for adding, updating, finding the category

- src/models/product/product.doc.ts
- src/services/product.service.ts
- src/types/model/product.type.ts
- src/utils/object.ts
- src/validations/product.valitdation.ts
- `isPublish` (optional): boolean
- `isActive` (optional): boolean
> chore: changed the isSolOut field to the isPublish field in Product & added isActive and isPublish filter

- src/constants/cloudinaryFolder.ts
- src/controllers/review.controller.ts
- src/middlewares/review.middleware.ts
- src/routers/v1/customerRoutes/index.ts
- src/routers/v1/customerRoutes/review.routes.ts
- src/routers/v1/index.ts
- src/routers/v1/review.route.ts
- src/services/review.service.ts
- src/types/http/review.type.ts
- src/validations/review.validation.ts
> feat: defined an API to creating new review product

- src/models/orderDetail/orderDetail.doc.ts
- src/services/order.service.ts
- src/services/orderDetail.service.ts
- src/types/http/orderDetails.type.ts
- src/types/model/order.type.ts
- src/types/model/orderDetail.type.ts
- src/validations/orderDetail.validation.ts
> chore: added the 'storeID' field into the OrderDetails model

- src/constants/httpMessage.ts
- src/controllers/review.controller.ts
- src/middlewares/review.middleware.ts
- src/models/review/review.doc.ts
- src/routers/v1/customerRoutes/review.routes.ts
- src/services/review.service.ts
- src/types/http/review.type.ts
- src/validations/review.validation.ts
- Send the `replyMessage` only if the store responds
> feat: defined an API to reacting the review

- src/models/order/order.doc.ts
- src/models/orderStageStatus/orderStageStatus.doc.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/services/order.service.ts
- src/services/orderStage.service.ts
- src/types/http/orderStage.type.ts
- src/utils/format.ts
- src/validations/orderStage.validation.ts
> chore: added the 'expectedDate' param to creating an order stage

- src/controllers/orderStageStatus.controller.ts
- src/routers/v1/customerRoutes/orderStageStatus.routes.ts
- src/services/orderStage.service.ts
- src/services/orderStageStatus.service.ts
- src/types/http/orderStageStatus.type.ts
- src/validations/orderStageStatus.validation.ts
> defined an API to updating lead date of order status

- src/services/orderStage.service.ts
- src/types/http/orderStage.type.ts
- src/validations/orderStage.validation.ts
- src/validations/orderStageStatus.validation.ts
> chore: added the "orderStageStatusID" params for create order stage api

- src/services/order.service.ts
- src/services/orderRequest.service.ts
- src/services/product.service.ts
- src/services/user.service.ts
- src/types/http/pagination.type.ts
- src/utils/object.ts
- src/validations/order.validation.ts
- src/validations/pagination.validation.ts
- `/orders` (for customer)
- `/se/orders` (for seller)
- `/ad/orders` (for admin)
```
userID (required if customer)
paymentMethodID:
orderStageID:
storeID (required if seller)
_id:
page: (required)
limit: (required)
search:
```
---
```
export interface PaginationResponseProps {
page: number;
limit: number;
total: number;
data: any[];
}
```
> feat: implemented the order functions

- src/constants/httpMessage.ts
- src/controllers/order.controller.ts
- src/controllers/store.controller.ts
- src/middlewares/errorHandler.middleware.ts
- src/middlewares/product.middleware.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/routers/v1/customerRoutes/store.routes.ts
- src/services/order.service.ts
- src/services/store.service.ts
- src/utils/catchErrors.ts
- src/utils/classes/ApiError.ts
- `data`: an array of products is out of stock
> perf: check product quantity before placing order

- src/constants/httpMessage.ts
- src/middlewares/product.middleware.ts
- src/routers/v1/customerRoutes/product.routes.ts
- src/services/order.service.ts
- src/services/product.service.ts
- _id
- statusCode
- massage
- data: [
{
- `_id`: Order details ID
- orderID : {
- `_id`: Order ID
- orderStageID: {
- `_id`: Order stage ID,
- `name`: Order stage name
}
}
}
]
> perf: added a middleware to check order status when deleting a product

- src/constants/routes.ts
- src/routers/v1/customerRoutes/order.routes.ts
- src/services/order.service.ts
```
interface TrackingOrderProps extends Pick<OrderStageProps, '_id' | 'name' | 'orderID'> {
orderStageStatus: (Omit<OrderStageStatusProps, 'orderRequestID'> & {
orderRequestID: Omit<OrderRequestProps, 'reasonID'> & {
reasonID: ReasonProps;
};
})[];
}
```
> feat: defined an API to tracking an order

- src/controllers/reason.controller.ts
- src/models/reason/reason.doc.ts
- src/routers/v1/reason.routes.ts
- src/services/reason.service.ts
- src/types/enum/taskType.enum.ts
- src/types/http/reason.type.ts
- src/types/model/reason.type.ts
- src/validations/reason.validation.ts
**Request Body**
- name: string
- objectType: ObjectType
- taskType: TaskType
- role: Role
**Response**
**Request Body**
- _id: ObjectID
- name: string
**Response**
> Ecom-33-reason: Added create and update reason functions

- src/constants/routes.ts
- src/controllers/adminControllers/dashboard.controller.ts
- src/routers/v1/adminRoutes/dashboard.routes.ts
- src/routers/v1/adminRoutes/index.ts
- src/routers/v1/adminRoutes/user.routes.ts
- src/routers/v1/customerRoutes/address.routes.ts
- src/routers/v1/customerRoutes/store.routes.ts
- src/routers/v1/customerRoutes/user.routes.ts
- src/services/admin.service.ts
- src/services/order.service.ts
- src/services/store.service.ts
- src/utils/object.ts
- startAt
- endAt
- storeID
---
> feat: statistic
